# Generated by Django 5.0.3 on 2024-06-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
